# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Project information
site_name: esead 
site_url: https://esead.github.io/
site_author: Superintendência de Educação Aberta e a Distância (SEAD)
site_description: >-
  Plataforma para disponibilização de e-books no formato App Web da Superintendência 
  de Educação Aberta e a Distância (SEAD) da Universidade Federal do Recôncavo da Bahia (UFRB).

# Repository
repo_name: esead
repo_url: https://github.com/esead/
edit_uri: ""

# Copyright
copyright: Copyright &copy; 2020 Superintendência de Educação Aberta e a Distância - SEAD/UFRB

# Configuration
theme:
  name: null
  custom_dir: material

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: pt
  features:
    - tabs
    #- instant
  palette:
    scheme: default
    primary: blue
    accent: blue
  font:
    text: Helvetica
    code: Roboto Mono
  icon:
    logo: logo
  favicon: assets/favicon.png

# Plugins
plugins:
  - macros
  - search
  - minify:
      minify_html: true

# Customization
extra:
  unit:
    price: 22.48
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/esead
    - icon: fontawesome/brands/facebook
      link: https://facebook.com/seadufrb
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/ufb_sead

# Extensions
# Equations
extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js
  - 'https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML'
markdown_extensions:
  - attr_list
  - def_list
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  # - pymdownx.highlight:
  #     linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      repo_url_shorthand: true
      user: squidfunk
      repo: mkdocs-material
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
  - Home: index.md
  - Sobre:
    - Home: sobre/index.md
  - Explore:
    - E-books: explore/index.md
  - Limite:
    - Definição: limite/definicao.md
    - Propriedades: limite/propriedades.md
    - Continuidade: limite/continuidade.md
    - Infinitos: limite/infinitos.md
    - No infinito: limite/no-infinito.md
    - Fundamentais: limite/fundamentais.md
    - Licença: limite/creative-commons.md 
  - O Papel do Fiscal na Administração Pública:
    - Capa: o-papel-do-fiscal-na-administracao-publica/capa.md
    - Autora: o-papel-do-fiscal-na-administracao-publica/contra-capa.md
    - Licença: o-papel-do-fiscal-na-administracao-publica/creative-commons.md
    - Produção: o-papel-do-fiscal-na-administracao-publica/producao.md
    - Apresentação: o-papel-do-fiscal-na-administracao-publica/apresentacao.md
    - Conceitos: o-papel-do-fiscal-na-administracao-publica/introducao.md
    - Definições: o-papel-do-fiscal-na-administracao-publica/definicoes.md
    - Fiscalização dos Contratos: o-papel-do-fiscal-na-administracao-publica/fiscalizacao-dos-contratos.md
    - Sugestões de orientações básicas aos fiscais: o-papel-do-fiscal-na-administracao-publica/sugestoes-fiscais.md
    - Legislação e sites oficiais: o-papel-do-fiscal-na-administracao-publica/legislacao-oficiais.md
    - Modelos dos formulários: o-papel-do-fiscal-na-administracao-publica/modelos-formularios.md
    - Referências: o-papel-do-fiscal-na-administracao-publica/referencias.md
    - Anexos: o-papel-do-fiscal-na-administracao-publica/anexos.md
    - Capa fundo: o-papel-do-fiscal-na-administracao-publica/capa-fundo.md
    - Videoaulas: o-papel-do-fiscal-na-administracao-publica/videoaulas.md
  - Leitura de Ambientes da Mineração:
    - Capa: leitura-de-ambientes-da-mineracao/capa.md
    - Autores: leitura-de-ambientes-da-mineracao/contra-capa.md
    - Licença: leitura-de-ambientes-da-mineracao/creative-commons.md
    - Produção: leitura-de-ambientes-da-mineracao/producao.md
    - Apresentação: leitura-de-ambientes-da-mineracao/apresentacao.md
    - Introdução: leitura-de-ambientes-da-mineracao/introducao.md
    - Ambiente Terrestre e Diversidade: leitura-de-ambientes-da-mineracao/ambiente.md
    - Recursos Minerais e Energéticos da Terra: leitura-de-ambientes-da-mineracao/recursos.md
    - Alterações do Ambiente pela Atividade de Mineração: leitura-de-ambientes-da-mineracao/alteracoes.md
    - Percepção e Análise Ambiental: leitura-de-ambientes-da-mineracao/percepcao.md
    - Ferramentas para a Leitura de Ambientes: leitura-de-ambientes-da-mineracao/ferramentas.md
    - Referências: leitura-de-ambientes-da-mineracao/referencias.md
    - Capa fundo: leitura-de-ambientes-da-mineracao/capa-fundo.md
  - Guia de Produção de Material Didático:
    - Capa: guia-de-producao-de-material-didatico/capa.md
    - Autor: guia-de-producao-de-material-didatico/contra-capa.md
    - Licença: guia-de-producao-de-material-didatico/creative-commons.md
    - Produção: guia-de-producao-de-material-didatico/producao.md
    - Guia de Produção: guia-de-producao-de-material-didatico/guia-de-producao.md
    - Acessibilidade em Materiais Didáticos: guia-de-producao-de-material-didatico/acessibilidade-materiais.md
    - Capa fundo: guia-de-producao-de-material-didatico/capa-fundo.md
  - Tecnologias e Educação Digital:
    - Capa: tecnologias-educacao-digital/capa.md
    - Organizadores: tecnologias-educacao-digital/contra-capa.md
    - Licença:  tecnologias-educacao-digital/creative-commons.md
    - Produção: tecnologias-educacao-digital/producao.md
    - Capítulo 1: tecnologias-educacao-digital/capitulo-1.md
    - Capítulo 2: tecnologias-educacao-digital/capitulo-2.md
    - Capítulo 3: tecnologias-educacao-digital/capitulo-3.md
    - Capítulo 4: tecnologias-educacao-digital/capitulo-4.md
    - Capítulo 5: tecnologias-educacao-digital/capitulo-5.md
    - Capítulo 6: tecnologias-educacao-digital/capitulo-6.md
    - Capítulo 7: tecnologias-educacao-digital/capitulo-7.md
    - Capítulo 8: tecnologias-educacao-digital/capitulo-8.md
    - Capítulo 9: tecnologias-educacao-digital/capitulo-9.md
    - Capítulo 10: tecnologias-educacao-digital/capitulo-10.md
    - Sobre Organizadores: tecnologias-educacao-digital/organizadores.md
    - Sobre Autores: tecnologias-educacao-digital/autores.md


  - Modelo Pedagógico Virtual UFRB:
    - Capa: modelo-pedagogico-virtual-ufrb/capa.md
    - Autores: modelo-pedagogico-virtual-ufrb/contra-capa.md
    - Licença:  modelo-pedagogico-virtual-ufrb/creative-commons.md
    - Produção: modelo-pedagogico-virtual-ufrb/producao.md
    - Nota prévia: modelo-pedagogico-virtual-ufrb/nota-previa.md
    - Prefácio: modelo-pedagogico-virtual-ufrb/prefacio.md
    - Capítulo 1: modelo-pedagogico-virtual-ufrb/capitulo-1.md
    - Capítulo 2: modelo-pedagogico-virtual-ufrb/capitulo-2.md
    - Capítulo 3: modelo-pedagogico-virtual-ufrb/capitulo-3.md
    - Capítulo 4: modelo-pedagogico-virtual-ufrb/capitulo-4.md
    - Referências: modelo-pedagogico-virtual-ufrb/referencias.md
    - Apêndices: modelo-pedagogico-virtual-ufrb/apendices.md
    - Capa fundo: modelo-pedagogico-virtual-ufrb/capa-fundo.md
  - II SITED - Anais:
    - Capa: ii-sited-anais/capa.md
    - Comissão Organizadora: ii-sited-anais/comissao-organizadora.md
    - Comitê Científico: ii-sited-anais/comite-cientifico.md
    - Licença: ii-sited-anais/creative-commons.md
    - Eixo I: ii-sited-anais/eixo-1.md
    - Capítulo 1: ii-sited-anais/capitulo-1.md
    - Capítulo 2: ii-sited-anais/capitulo-2.md
    - Capítulo 3: ii-sited-anais/capitulo-3.md
    - Capítulo 4: ii-sited-anais/capitulo-4.md
    - Capítulo 5: ii-sited-anais/capitulo-5.md
    - Capítulo 6: ii-sited-anais/capitulo-6.md
    - Capítulo 7: ii-sited-anais/capitulo-7.md
    - Capítulo 8: ii-sited-anais/capitulo-8.md
    - Capítulo 9: ii-sited-anais/capitulo-9.md
    - Capítulo 10: ii-sited-anais/capitulo-10.md
    - Capítulo 11: ii-sited-anais/capitulo-11.md
    - Capítulo 12: ii-sited-anais/capitulo-12.md
    - Capítulo 13: ii-sited-anais/capitulo-13.md
    - Capítulo 14: ii-sited-anais/capitulo-14.md
    - Capítulo 15: ii-sited-anais/capitulo-15.md
    - Eixo II: ii-sited-anais/eixo-2.md
    - Capítulo 16: ii-sited-anais/capitulo-16.md
    - Capítulo 17: ii-sited-anais/capitulo-17.md
    - Eixo III: ii-sited-anais/eixo-3.md
    - Capítulo 18: ii-sited-anais/capitulo-18.md
    - Capa fundo: ii-sited-anais/capitulo-fundo.md
  - Derivada:
    - Definição: derivada/definicao.md
    - Propriedades: derivada/propriedades.md
    - Licença: derivada/creative-commons.md
  - Aplicações:
    - Definição: aplicacao/definicao.md
    - Propriedades: aplicacao/propriedades.md
    - Licença: aplicacao/creative-commons.md
  - Integral:
    - Definição: integral/definicao.md
    - Propriedades: integral/propriedades.md
    - Licença: integral/creative-commons.md
  - Listas:
    - Limite: listas/limite.md
    - Derivada: listas/derivada.md
    - Aplicações: listas/aplicacao.md
    - Integral: listas/integral.md
    - Licença: derivada/creative-commons.md
# Google Analytics
google_analytics:
  - !!python/object/apply:os.getenv ["GOOGLE_ANALYTICS_KEY"]
  - auto
